from constans import FormatSpecifier

edit_step_num_format_data = [
    {'id': 'step_num1', 'left': '620px', 'top': '40px', 'text': '1'},
    {'id': 'step_num2', 'left': '620px', 'top': '40px', 'text': '1'},
    {'id': 'step_num3', 'left': '620px', 'top': '40px', 'text': '1'},
    {'id': 'step_num4', 'left': '620px', 'top': '40px', 'text': '1'},
    {'id': 'step_num5', 'left': '620px', 'top': '40px', 'text': '1'},
    {'id': 'step_num6', 'left': '620px', 'top': '40px', 'text': '1'},
]

NEWLINE = '<br>'
edit_dev_format_data = [
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'RFセットパワー'+NEWLINE+'(W)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': '温度設定'+NEWLINE+'(℃)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': '温度設定'+NEWLINE+'(℃)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'H2 マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'CH4 マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'O2 マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'Ar マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'N2 マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'H2 マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'Ar マスフロー'+NEWLINE+'(sccm)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'A室角度'+NEWLINE+'(° )'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'B室角度'+NEWLINE+'(° )'},
    # {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'ヒーター昇降'+NEWLINE+'(mm)'},
    # {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'ヒーター昇降速度'+NEWLINE+'(mm/s)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM2 開度調整'+NEWLINE+'(%)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM2 圧力調整'+NEWLINE+'(Pa)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM3 フォイル搬送'+NEWLINE+'速度(cm/min)'},
    # {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM3 加速時間'+NEWLINE+'(sec)'},
    # {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM3 減速時間'+NEWLINE+'(sec)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM3 テンション制御'+NEWLINE+'速度上限(cm/min)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM3 テンション制御'+NEWLINE+'速度下限(cm/min)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM4 フォイル搬送'+NEWLINE+'速度(cm/min)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM4 テンション制御'+NEWLINE+'速度上限(cm/min)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM4 テンション制御'+NEWLINE+'速度下限(cm/min)'},
    # {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM4 加速時間'+NEWLINE+'(sec)'},
    # {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'SVM4 減速時間'+NEWLINE+'(sec)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': '時間'+NEWLINE+'(min)'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': '排気ステップ圧力'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': '排気・ステップ制御選択'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'A室回転方向'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'B室回転方向'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'A室テンション制御'+NEWLINE+'監視先'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'B室テンション制御'+NEWLINE+'監視先'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': '巻径演算'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'PGAS1 使用'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'PGAS2 使用'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'PGAS3 使用'},
    {'id': 'reci1_num1_dev', 'left': '8px', 'top': '200px', 'text': 'PGAS4 使用'},

]

edit_monitor_format_data = [
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6004, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6020, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6022, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6034, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6036, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6038, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6040, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6042, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6044, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6046, 'format': FormatSpecifier.F3_1},

    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6026, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6028, 'format': FormatSpecifier.F3_1},
    # {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6092, 'format': FormatSpecifier.F3_1},
    # {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6094, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6002, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6096, 'format': FormatSpecifier.F3_1},
    # {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6100, 'format': FormatSpecifier.F3_1},
    # {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6102, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},

    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6104, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    # {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6108, 'format': FormatSpecifier.F3_1},
    # {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 6110, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.F3_1},

    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.D},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.D},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.D},
    {'id': 'reci_num1_PV', 'left': '488px','top': '100px', 'address': 0, 'format': FormatSpecifier.D},
]

edit_textbox_format_data = [
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5000, 'data_index': 0, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'RF1 RFセットパワー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5002, 'data_index': 1, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'H1 温度設定', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5004, 'data_index': 2, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'H2 温度設定', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5006, 'data_index': 3, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG1 H2マスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5008, 'data_index': 4, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG2 CH4マスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5010, 'data_index': 5, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG3 O2マスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5012, 'data_index': 6, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG4 Arマスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5014, 'data_index': 7, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG5 N2マスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5016, 'data_index': 8, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG6 H2マスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5018, 'data_index': 9, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'MFCG7 Arマスフロー', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5020, 'data_index': 10, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'EC1 A室角度', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5022, 'data_index': 11, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'EC2 B室角度', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    # {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5024, 'data_index': 12, 'input_format': 'REAL',
    #     'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
    #     'name': 'SVM1 ヒーター昇降位置', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    # {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5026, 'data_index': 13, 'input_format': 'REAL',
    #     'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
    #     'name': 'SVM1 ヒーター昇降速度', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5028, 'data_index': 14, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM2 開度調整', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5030, 'data_index': 15, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM2 圧力調整', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5032, 'data_index': 16, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM3 フォイル搬送速度', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    # {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5034, 'data_index': 17, 'input_format': 'REAL',
    #     'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
    #     'name': 'SVM3 加速時間', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    # {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5036, 'data_index': 18, 'input_format': 'REAL',
    #     'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
    #     'name': 'SVM3 減速時間', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5038, 'data_index': 19, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM3 テンション制御速度上限', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5040, 'data_index': 20, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM3 テンション制御速度下限', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5042, 'data_index': 21, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM4 フォイル搬送速度', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5044, 'data_index': 22, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM4 テンション制御速度上限', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5046, 'data_index': 23, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': 'SVM4 テンション制御速度下限', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    # {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5048, 'data_index': 24, 'input_format': 'REAL',
    #     'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
    #     'name': 'SVM4 加速時間', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    # {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5050, 'data_index': 25, 'input_format': 'REAL',
    #     'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
    #     'name': 'SVM4 減速時間', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5052, 'data_index': 26, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': '時間', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5054, 'data_index': 27, 'input_format': 'REAL',
        'format': FormatSpecifier.F3_1, 'trigger_id': 'reci_num1_trigger',
        'name': '排気ステップ圧力', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5060, 'data_index': 30, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': '排気ステップ制御選択', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5061, 'data_index': 31, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'A室回転方向', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5062, 'data_index': 32, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'B室回転方向', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5063, 'data_index': 33, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'A室テンション制御監視先', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5064, 'data_index': 34, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'B室テンション制御監視先', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5065, 'data_index': 35, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': '巻径演算', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5066, 'data_index': 36, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'PGAS1 使用', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5067, 'data_index': 37, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'PGAS2 使用', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5068, 'data_index': 38, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'PGAS3 使用', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    {'id': 'reci_num1_SV', 'left': '356px','top': '8px', 'address': 5069, 'data_index': 39, 'input_format': 'UINT',
        'format': FormatSpecifier.D, 'trigger_id': 'reci_num1_trigger',
        'name': 'PGAS4 使用', 'min_value': 0.0, 'max_value': 500.0, 'file': False},
    
]